version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: python:3.11-alpine
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "8080:80"

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:80"
